# Generated by Django 5.1.1 on 2024-09-30 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='У этой секции нет описания', max_length=500)),
                ('location', models.CharField(default='СК МГТУ', max_length=200)),
                ('date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=90)),
                ('imageUrl', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалёна'), ('created', 'Сформирована'), ('completed', 'Завершёна'), ('rejected', 'Отклонёна')], default='draft', max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('apply_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_sections', models.IntegerField(default=0)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_app.application')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_app.section')),
            ],
            options={
                'db_table': 'priority',
                'unique_together': {('application', 'section')},
            },
        ),
    ]
