# Generated by Django 5.1.1 on 2024-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number_of_sections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалена'), ('created', 'Сформирована'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='draft', max_length=50),
        ),
    ]
