# Generated by Django 5.1.3 on 2024-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_app', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='classroom',
            field=models.CharField(blank=True, null=True),
        ),
    ]
