# Generated by Django 5.1.1 on 2024-10-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_app', '0003_alter_priority_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
