# Generated by Django 5.1.1 on 2024-10-06 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_app', '0004_alter_priority_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='section',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
