# Generated by Django 5.1.1 on 2024-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_app', '0005_alter_section_date_alter_section_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.CharField(default='Петров Петр Петрович', max_length=100),
        ),
    ]
